README updated:
CSSS/wall_e pull request #421
Opened 2023-09-26 18:24 UTC by ashharr

Solves #415 

## Description

## PR Checklist

These are the things you need to ensure are covered in your PR, otherwise the CODEOWNERS will not approve your PR, not matter how much you ping them to do so on the Discord  
  
 1. The description in the PR is a fair representation of what the PR is about.
 1. The PR is fixing one thing and one thing only.
 1. Logging. if you have N variables initialzed/used in your function, you should print all of them out to the log using logging module at least once or have a good reason why you arent.
 1. If your PR is doing something like adding a new line or removing a new line, CODEOWNERS reserve the right to ask that you undo that change unless it was for a specific reason.
 1. If you are adding a new command....document. Document the following things on help.json and the README.md
    1. The purpose of the command
    1. If the argument is called with any arguments.
       1. If it is called with any arguments, please either provide a good enough explanation of the arg that a user can tell what it will do before using the command. adding an example of how to call it with the args is not necessary but good practice.
 1. If you are making a new Class of commands, add the class to bot.json following the convention already there.
 1. Evidence of Testing. This one needs to be completed after the PR is opened. At that point, you will go on the channel on the CSSS Wall-E Test Server that was automatically created when the PR was opened and then test the [following functionality](https://github.com/CSSS/wall_e/blob/master/documentation/Working_on_Bot/Test_Cases.md). Once you had done so, you can leave a comment on the PR stating that you had done the necessary testing.
 1. Please provide ways to test whatever you just modified on the bot in the [Test Cases section](https://github.com/CSSS/wall_e/blob/master/documentation/Working_on_Bot/Test_Cases.md) so that future PRs can be tested to ensure they dont break your code when merging to master

2023-09-26 18:52 UTC, modernNeo requested changes

2023-09-26 18:52 UTC, modernNeo commented on README.md
> +### Additional Resources
this README is not for dev work instructions, dev work should be in the `How to work on the bot` README

2023-09-27 12:30 UTC, ashharr commented
removed it and added it there. please review.

2023-09-27 20:24 UTC, modernNeo commented
please clean the commit history so that you are modifying only the `How to work on the bot` README. do you know how to do that?

2023-09-30 19:11 UTC, ashharr commented
> please clean the commit history so that you are modifying only the `How to work on the bot` README. do you know how to do that?

nope, is there a quick command to clean commit history?

2023-10-02 00:42 UTC, modernNeo commented
are you on the CSSS discord guild?

2023-10-02 11:33 UTC, ashharr commented
no. can you add me there, my user tag is @electrohead

2023-10-02 18:24 UTC, modernNeo commented
> no. can you add me there, my user tag is @electrohead

sorry, you are not on the guild but I can tag you there with that username?

2023-10-02 22:05 UTC, modernNeo commented
> no. can you add me there, my user tag is @electrohead

just join via http://discord.sfucsss.org/

2023-10-08 08:13 UTC, modernNeo commented
PR no longer needed now that documentation has been moved to README

2023-10-08 08:13 UTC, closed without merging